# Generated by Django 4.1 on 2022-08-20 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_id', models.CharField(max_length=50, unique=True)),
                ('Email_id', models.EmailField(max_length=100, unique=True)),
                ('Account_Name', models.CharField(max_length=100)),
                ('Secret_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
